export const fetchBooks = async () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([

                {
                    "id_livro": 1,
                    "titulo": "Veneno",
                    "autor": "Sarah Pinborough",
                    "imagem_url": "https://m.media-amazon.com/images/I/51SJLhPPr5L._SY445_SX342_.jpg",
                    "trecho_livro": "Um enredo envolvente que explora a complexidade das relacoes humanas.",
                    "comentario_livro": "Veneno e uma narrativa intrigante que mistura elementos de fantasia e misterio, mantendo o leitor preso do comeco ao fim. Uma leitura recomendada para os amantes do genero.",
                    "classificacao_livro": 4,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "encantadas"
                },
                {
                    "id_livro": 2,
                    "titulo": "Feitico",
                    "autor": "Sarah Pinborough",
                    "imagem_url": "https://m.media-amazon.com/images/I/51wAVN7bRnL._SY445_SX342_.jpg",
                    "trecho_livro": "A magia pode ser tanto uma bencao quanto uma maldicao.",
                    "comentario_livro": "Feitico e uma obra que desafia a percepcao do que e real e o que e ilusao, com personagens bem desenvolvidos e reviravoltas surpreendentes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "encantadas"
                },
                {
                    "id_livro": 4,
                    "titulo": "A maldicao do tigre",
                    "autor": "Colleen Houck",
                    "imagem_url": "https://m.media-amazon.com/images/I/512unAmVinL._SY445_SX342_.jpg",
                    "trecho_livro": "A jornada de um amor proibido entre mundos diferentes.",
                    "comentario_livro": "A maldicao do tigre e uma mistura de romance e aventura, com uma narrativa rica que transporta o leitor para um mundo magico e cheio de desafios.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "a maldicao do tigre"
                },
                {
                    "id_livro": 5,
                    "titulo": "O destino do tigre",
                    "autor": "Colleen Houck",
                    "imagem_url": "https://m.media-amazon.com/images/I/5111it2ukyL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor pode superar qualquer obstaculo.",
                    "comentario_livro": "Uma continuacao emocionante que aprofunda os lacos entre os personagens, O destino do tigre e uma leitura que cativa e emociona.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "a maldicao do tigre"
                },
                {
                    "id_livro": 6,
                    "titulo": "O resgate do tigre",
                    "autor": "Colleen Houck",
                    "imagem_url": "https://m.media-amazon.com/images/I/51s9QlRXwuL._SY445_SX342_.jpg",
                    "trecho_livro": "A luta pela liberdade e pelo amor verdadeiro.",
                    "comentario_livro": "O resgate do tigre e uma obra que combina acao e romance, mantendo o leitor ansioso por cada pagina. Uma historia de coragem e amor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "a maldicao do tigre"
                },
                {
                    "id_livro": 7,
                    "titulo": "A viagem do tigre",
                    "autor": "Colleen Houck",
                    "imagem_url": "https://m.media-amazon.com/images/I/51O1ri0K+SL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma jornada que desafia os limites do amor.",
                    "comentario_livro": "A viagem do tigre e uma conclusao epica que amarra todas as pontas soltas da serie, proporcionando um desfecho satisfatorio e emocionante.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "a maldicao do tigre"
                },
                {
                    "id_livro": 8,
                    "titulo": "A sensitiva",
                    "autor": "Hannah Howell",
                    "imagem_url": "https://m.media-amazon.com/images/I/61AMYINn7PL._SY425_.jpg",
                    "trecho_livro": "O dom da percepcao pode ser tanto uma bencao quanto uma maldicao.",
                    "comentario_livro": "A sensitiva e uma narrativa envolvente que explora o mundo sobrenatural, com personagens cativantes e uma trama intrigante que mantem o leitor atento.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "a sensitiva"
                },
                {
                    "id_livro": 9,
                    "titulo": "A intuitiva",
                    "autor": "Hannah Howell",
                    "imagem_url": "https://m.media-amazon.com/images/I/41KJ4HD2OxL._SX342_SY445_.jpg",
                    "trecho_livro": "A intuicao pode guiar o caminho em tempos de incerteza.",
                    "comentario_livro": "A intuitiva e uma obra que combina romance e misterio, levando o leitor a uma jornada de autodescoberta e revelacoes surpreendentes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "a sensitiva"
                },
                {
                    "id_livro": 10,
                    "titulo": "A vidente",
                    "autor": "Hannah Howell",
                    "imagem_url": "https://m.media-amazon.com/images/I/51hlPNfzfzL._SY425_.jpg",
                    "trecho_livro": "Visoes do futuro podem alterar o presente.",
                    "comentario_livro": "A vidente e uma historia que entrelaca o sobrenatural com o cotidiano, proporcionando uma leitura fascinante e cheia de reviravoltas.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "a sensitiva"
                },
                {
                    "id_livro": 11,
                    "titulo": "A selecao",
                    "autor": "Kiera Cass",
                    "imagem_url": "https://m.media-amazon.com/images/I/510XEt4RMSL._SY445_SX342_.jpg",
                    "trecho_livro": "Um concurso que pode mudar o destino de uma nacao.",
                    "comentario_livro": "A selecao e uma historia de amor e competicao, com personagens bem construidos e um enredo que prende a atencao do inicio ao fim.",
                    "classificacao_livro": 5,
                    "categoria_nome": "drama",
                    "colecao_nome": "a selecao"
                },
                {
                    "id_livro": 12,
                    "titulo": "A elite",
                    "autor": "Kiera Cass",
                    "imagem_url": "https://m.media-amazon.com/images/I/51egaVAWAbL._SY445_SX342_.jpg",
                    "trecho_livro": "A pressao aumenta à medida que a competicao se intensifica.",
                    "comentario_livro": "A elite e uma continuacao emocionante que aprofunda os conflitos e dilemas dos personagens, mantendo o leitor ansioso por mais.",
                    "classificacao_livro": 5,
                    "categoria_nome": "drama",
                    "colecao_nome": "a selecao"
                },
                {
                    "id_livro": 13,
                    "titulo": "A escolha",
                    "autor": "Kiera Cass",
                    "imagem_url": "https://m.media-amazon.com/images/I/81htmSSRhXL._SY425_.jpg",
                    "trecho_livro": "Decisoes dificeis podem moldar o futuro.",
                    "comentario_livro": "A escolha e um desfecho emocionante que traz à tona os dilemas do amor e do dever, proporcionando uma conclusao satisfatoria para a serie.",
                    "classificacao_livro": 5,
                    "categoria_nome": "drama",
                    "colecao_nome": "a selecao"
                },
                {
                    "id_livro": 3,
                    "titulo": "Poder",
                    "autor": "Sarah Pinborough",
                    "imagem_url": "https://m.media-amazon.com/images/I/51Nalk3QhyL._SY445_SX342_.jpg",
                    "trecho_livro": "O poder da feiticaria pode mudar destinos.",
                    "comentario_livro": "Uma historia que explora os limites da magia e suas consequencias, Feitico e uma leitura que provoca reflexao sobre escolhas e suas repercussoes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "encantadas"
                },
                {
                    "id_livro": 28,
                    "titulo": "Revolucao dos bichos",
                    "autor": "George Orwell",
                    "imagem_url": "https://m.media-amazon.com/images/I/61owA5ey3iL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma fabula sobre poder e corrupcao.",
                    "comentario_livro": "Revolucao dos bichos e uma critica social poderosa que utiliza animais para explorar temas de opressao e revolta, sendo uma leitura essencial.",
                    "classificacao_livro": 5,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 29,
                    "titulo": "Elas nao usam black-tie",
                    "autor": "Gianfrancesco Guarnieri",
                    "imagem_url": "https://m.media-amazon.com/images/I/51CYSjj8GdL._SY445_SX342_.jpg",
                    "trecho_livro": "Um retrato da luta de classes e da resistencia.",
                    "comentario_livro": "Elas nao usam black-tie e uma obra que aborda questoes sociais e politicas com profundidade, apresentando personagens complexos e um enredo envolvente.",
                    "classificacao_livro": 5,
                    "categoria_nome": "teatro",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 30,
                    "titulo": "Quem tem medo de vampiro?",
                    "autor": "Dalton Trevisan",
                    "imagem_url": "https://m.media-amazon.com/images/I/91bGIYnfEjL._SY425_.jpg",
                    "trecho_livro": "Uma reflexao sobre medos e fantasias.",
                    "comentario_livro": "Quem tem medo de vampiro? e uma narrativa que mistura humor e critica social, desafiando o leitor a confrontar seus proprios medos e preconceitos.",
                    "classificacao_livro": 4,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 31,
                    "titulo": "Playboy irresistivel",
                    "autor": "Christina Lauren",
                    "imagem_url": "https://m.media-amazon.com/images/I/51fYxBaeaWL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor pode surgir nos lugares mais inesperados.",
                    "comentario_livro": "Playboy irresistivel e uma comedia romântica leve e divertida, com personagens carismaticos e uma trama que faz o coracao bater mais forte.",
                    "classificacao_livro": 4,
                    "categoria_nome": "romance",
                    "colecao_nome": "playboy"
                },
                {
                    "id_livro": 32,
                    "titulo": "Redencao e submissao",
                    "autor": "Nana Pauvolih",
                    "imagem_url": "https://m.media-amazon.com/images/I/91dGME4FJkL._SY425_.jpg",
                    "trecho_livro": "Uma jornada de autodescoberta e aceitacao.",
                    "comentario_livro": "Redencao e submissao e uma obra que explora temas de amor e poder, desafiando as normas sociais e emocionando o leitor com sua profundidade.",
                    "classificacao_livro": 4,
                    "categoria_nome": "romance",
                    "colecao_nome": "redencao e submissao"
                },
                {
                    "id_livro": 33,
                    "titulo": "O escaravelho do diabo",
                    "autor": "Lucia Machado",
                    "imagem_url": "https://m.media-amazon.com/images/I/51offhcp4OL._SY445_SX342_.jpg",
                    "trecho_livro": "Um misterio que envolve o sobrenatural.",
                    "comentario_livro": "O escaravelho do diabo e uma narrativa intrigante que mistura suspense e elementos sobrenaturais, mantendo o leitor em constante expectativa.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 34,
                    "titulo": "Depois de voce",
                    "autor": "Jojo Moyes",
                    "imagem_url": "https://m.media-amazon.com/images/I/41M-QPmjLRL._SY445_SX342_.jpg",
                    "trecho_livro": "A vida continua, mesmo apos grandes perdas.",
                    "comentario_livro": "Depois de voce e uma historia tocante sobre superacao e amor, que explora as complexidades das relacoes humanas de forma sensivel.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "depois de voce"
                },
                {
                    "id_livro": 35,
                    "titulo": "Relacoes de sangue",
                    "autor": "Martha Argel",
                    "imagem_url": "https://m.media-amazon.com/images/I/81T0mn4XwCL._SY425_.jpg",
                    "trecho_livro": "Lacos que vao alem do sangue.",
                    "comentario_livro": "Relacoes de sangue e uma narrativa que explora a complexidade das relacoes familiares, com personagens bem construidos e uma trama envolvente.",
                    "classificacao_livro": 4,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 37,
                    "titulo": "Se houver amanha",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/71waotYYOrL._SY425_.jpg",
                    "trecho_livro": "O futuro e incerto, mas as escolhas sao nossas.",
                    "comentario_livro": "Se houver amanha e uma narrativa envolvente que explora as consequencias das decisoes tomadas, com reviravoltas que surpreendem o leitor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 38,
                    "titulo": "Em busca de um novo amanha",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/51-2oEdu2xL._SY445_SX342_.jpg",
                    "trecho_livro": "A esperanca renasce mesmo nas piores circunstâncias.",
                    "comentario_livro": "Em busca de um novo amanha e uma historia inspiradora sobre resiliencia e a busca por um futuro melhor, com personagens que cativam o leitor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 39,
                    "titulo": "Um estranho no espelho",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/41Wo5e+usEL._SY445_SX342_.jpg",
                    "trecho_livro": "Reflexoes sobre identidade e autoaceitacao.",
                    "comentario_livro": "Um estranho no espelho e uma narrativa que provoca reflexoes profundas sobre quem somos e como nos vemos, com uma trama envolvente.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 40,
                    "titulo": "Anjo da escuridao",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/41gSRMBiWjL._SY445_SX342_.jpg",
                    "trecho_livro": "Os segredos do passado podem assombrar o presente.",
                    "comentario_livro": "Anjo da escuridao e uma obra que mistura misterio e drama, mantendo o leitor intrigado ate a última pagina.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 41,
                    "titulo": "Depois da escuridao",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/51psOjqvW8L._SY445_SX342_.jpg",
                    "trecho_livro": "A luz pode surgir mesmo nas trevas mais profundas.",
                    "comentario_livro": "Depois da escuridao e uma narrativa que explora a luta pela superacao e a busca por esperanca, com personagens que ressoam com o leitor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 42,
                    "titulo": "Lembrancas da meia-noite",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/71ul+6k6TvL._SY425_.jpg",
                    "trecho_livro": "Memorias que moldam o presente.",
                    "comentario_livro": "Lembrancas da meia-noite e uma obra que entrelaca passado e presente, revelando segredos que impactam a vida dos personagens.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 43,
                    "titulo": "O outro lado da meia-noite",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/71dXRmjuE8L._SY425_.jpg",
                    "trecho_livro": "A dualidade da vida e suas consequencias.",
                    "comentario_livro": "O outro lado da meia-noite e uma narrativa envolvente que explora os limites entre amor e vinganca, mantendo o leitor em suspense ate o final.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 44,
                    "titulo": "Conte me seus sonhos",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/41fE5B1wtrL._SY445_SX342_.jpg",
                    "trecho_livro": "Os sonhos podem revelar verdades ocultas.",
                    "comentario_livro": "Conte me seus sonhos e uma obra que mistura misterio e drama psicologico, levando o leitor a questionar a realidade e a natureza dos sonhos.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 45,
                    "titulo": "Um capricho dos deuses",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/417752WSS2L._SY445_SX342_.jpg",
                    "trecho_livro": "A sorte pode mudar em um instante.",
                    "comentario_livro": "Um capricho dos deuses e uma narrativa que explora a fragilidade da vida e as reviravoltas do destino, mantendo o leitor intrigado ate a última pagina.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 46,
                    "titulo": "Algo a mais",
                    "autor": "Elinor Glyn",
                    "imagem_url": "https://m.media-amazon.com/images/I/41j4ADotUVL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor pode ser complicado e surpreendente.",
                    "comentario_livro": "Algo a mais e uma historia que explora as nuances do amor e do desejo, com personagens cativantes e um enredo envolvente.",
                    "classificacao_livro": 4,
                    "categoria_nome": "romance",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 47,
                    "titulo": "O enigma da casa de vidro",
                    "autor": "Ganymedes Jose",
                    "imagem_url": "https://m.media-amazon.com/images/I/412n4WidCWL.jpg",
                    "trecho_livro": "Misterios que desafiam a logica.",
                    "comentario_livro": "O enigma da casa de vidro e uma narrativa intrigante que combina suspense e misterio, mantendo o leitor em constante expectativa.",
                    "classificacao_livro": 4,
                    "categoria_nome": "drama",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 48,
                    "titulo": "Amante sombrio",
                    "autor": "J. R. Ward",
                    "imagem_url": "https://m.media-amazon.com/images/I/41Xip5hpyzL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor pode ser uma forca poderosa e perigosa.",
                    "comentario_livro": "Amante sombrio e uma narrativa que mistura romance e acao, com personagens complexos e um enredo que prende a atencao do inicio ao fim.",
                    "classificacao_livro": 5,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "irmandade da adaga negra"
                },
                {
                    "id_livro": 36,
                    "titulo": "A ira dos anjos",
                    "autor": "Sidney Sheldon",
                    "imagem_url": "https://m.media-amazon.com/images/I/41jOy0shL3L._SY445_SX342_.jpg",
                    "trecho_livro": "A luta entre o bem e o mal se intensifica.",
                    "comentario_livro": "A ira dos anjos e uma obra que combina suspense e drama, mantendo o leitor em constante tensao e expectativa sobre o desfecho da historia.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sidney Sheldon"
                },
                {
                    "id_livro": 49,
                    "titulo": "Cesar",
                    "autor": "Allan Massie",
                    "imagem_url": "https://m.media-amazon.com/images/I/81dEu3U6sxS._SY425_.jpg",
                    "trecho_livro": "A historia de um lider que moldou o mundo.",
                    "comentario_livro": "Cesar e uma obra que explora a vida e os feitos de um dos maiores lideres da historia, com uma narrativa rica e envolvente.",
                    "classificacao_livro": 4,
                    "categoria_nome": "historia",
                    "colecao_nome": "imperadores romanos"
                },
                {
                    "id_livro": 50,
                    "titulo": "Augusto",
                    "autor": "Allan Massie",
                    "imagem_url": "https://m.media-amazon.com/images/I/51srfZkIbKS._SY445_SX342_.jpg",
                    "trecho_livro": "O legado de um imperador.",
                    "comentario_livro": "Augusto e uma narrativa que explora a asc ensao e os desafios de um dos imperadores mais influentes da historia, oferecendo uma visao fascinante sobre o poder e a politica.",
                    "classificacao_livro": 4,
                    "categoria_nome": "historia",
                    "colecao_nome": "imperadores romanos"
                },
                {
                    "id_livro": 51,
                    "titulo": "Os caes sonham?",
                    "autor": "Stanley Coren",
                    "imagem_url": "https://m.media-amazon.com/images/I/51ZeYKpFlqL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma exploracao do mundo canino e suas emocoes.",
                    "comentario_livro": "Os caes sonham? e uma obra que investiga a psicologia dos caes, revelando como eles percebem o mundo e suas interacoes com os humanos.",
                    "classificacao_livro": 5,
                    "categoria_nome": "psicologia",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 52,
                    "titulo": "Morte e vida severina",
                    "autor": "Joao Cabral",
                    "imagem_url": "https://m.media-amazon.com/images/I/41wrVE0g8aL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma reflexao poetica sobre a vida e a morte.",
                    "comentario_livro": "Morte e vida severina e uma obra que aborda a condicao humana de forma profunda e sensivel, utilizando a poesia para transmitir suas mensagens.",
                    "classificacao_livro": 5,
                    "categoria_nome": "poesia",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 53,
                    "titulo": "Malorie",
                    "autor": "Josh Malerman",
                    "imagem_url": "https://m.media-amazon.com/images/I/41W-tr7++IL._SY445_SX342_.jpg",
                    "trecho_livro": "A luta pela sobrevivencia em um mundo apocaliptico.",
                    "comentario_livro": "Malorie e uma narrativa tensa e envolvente que explora o medo e a resiliencia em um cenario de desespero, mantendo o leitor em constante suspense.",
                    "classificacao_livro": 5,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 54,
                    "titulo": "Os sete",
                    "autor": "Andre Vianco",
                    "imagem_url": "https://m.media-amazon.com/images/I/31Z-2YPTnuL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma historia de vampiros e suas complexidades.",
                    "comentario_livro": "Os sete e uma obra que mistura elementos de terror e fantasia, apresentando uma narrativa rica em detalhes e personagens intrigantes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "trigesimo"
                },
                {
                    "id_livro": 55,
                    "titulo": "Bento",
                    "autor": "Andre Vianco",
                    "imagem_url": "https://m.media-amazon.com/images/I/41TNubviCrL._SY445_SX342_.jpg",
                    "trecho_livro": "A busca por identidade em um mundo caotico.",
                    "comentario_livro": "Bento e uma narrativa que explora a luta interna de um personagem em busca de seu lugar no mundo, com uma trama envolvente e reflexiva.",
                    "classificacao_livro": 4,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "trigesimo"
                },
                {
                    "id_livro": 56,
                    "titulo": "O morro dos ventos uivantes",
                    "autor": "Emily Bronte",
                    "imagem_url": "https://m.media-amazon.com/images/I/518EKRGVwkL._SY445_SX342_.jpg",
                    "trecho_livro": "Um amor intenso e destrutivo.",
                    "comentario_livro": "O morro dos ventos uivantes e uma obra-prima da literatura que explora as complexidades do amor e da vinganca, com uma narrativa poderosa e emocional.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 57,
                    "titulo": "Amor vampiro",
                    "autor": "Andre Vianco",
                    "imagem_url": "https://m.media-amazon.com/images/I/81ZKrqbx8-L._SY425_.jpg",
                    "trecho_livro": "Um romance que desafia as convencoes.",
                    "comentario_livro": "Amor vampiro e uma narrativa que mistura romance e elementos sobrenaturais, proporcionando uma leitura envolvente e cheia de surpresas, com personagens que cativam e intrigam.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 58,
                    "titulo": "As violetas de marco",
                    "autor": "Sarah Jio",
                    "imagem_url": "https://m.media-amazon.com/images/I/51WjOMnpsGL._SY445_SX342_.jpg",
                    "trecho_livro": "A beleza das flores pode esconder segredos profundos.",
                    "comentario_livro": "As violetas de marco e uma historia tocante que entrelaca amor e perda, explorando a forca das memorias e a importância das relacoes.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 59,
                    "titulo": "Ardente em chamas",
                    "autor": "Sylvia Day",
                    "imagem_url": "https://m.media-amazon.com/images/I/51Hl26cOfUL._SY445_SX342_.jpg",
                    "trecho_livro": "O desejo pode ser uma forca avassaladora.",
                    "comentario_livro": "Ardente em chamas e uma narrativa sensual que explora a paixao e os limites do amor, com personagens que desafiam as convencoes.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sylvia Day"
                },
                {
                    "id_livro": 60,
                    "titulo": "Um olhar de amor",
                    "autor": "Bella Andre",
                    "imagem_url": "https://m.media-amazon.com/images/I/41jZsUmQVQL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor pode surgir de onde menos se espera.",
                    "comentario_livro": "Um olhar de amor e uma historia romântica que captura a essencia do amor verdadeiro, com personagens que se conectam de maneira profunda.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Bella Andre"
                },
                {
                    "id_livro": 61,
                    "titulo": "Nao posso me apaixonar",
                    "autor": "Bella Andre",
                    "imagem_url": "https://m.media-amazon.com/images/I/51egPSAny1L._SY445_SX342_.jpg",
                    "trecho_livro": "O medo de se abrir pode ser paralisante.",
                    "comentario_livro": "Nao posso me apaixonar e uma narrativa que explora os desafios do amor e da vulnerabilidade, com personagens que lutam contra seus proprios medos.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Bella Andre"
                },
                {
                    "id_livro": 62,
                    "titulo": "Rush sem limites",
                    "autor": "Abbi Glines",
                    "imagem_url": "https://m.media-amazon.com/images/I/51bH6XN0FxL._SY445_SX342_.jpg",
                    "trecho_livro": "A adrenalina pode ser viciante.",
                    "comentario_livro": "Rush sem limites e uma historia que combina romance e emocao, com personagens que enfrentam desafios e descobrem o verdadeiro amor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Rush"
                },
                {
                    "id_livro": 64,
                    "titulo": "Crescendo",
                    "autor": "Becca Fitzpatrick",
                    "imagem_url": "https://m.media-amazon.com/images/I/81e7PGyapQL._SY425_.jpg",
                    "trecho_livro": "O amor pode ser complicado e cheio de desafios.",
                    "comentario_livro": "Crescendo e uma historia que mistura romance e misterio, com personagens que enfrentam dilemas emocionais e descobertas surpreendentes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "Becca"
                },
                {
                    "id_livro": 65,
                    "titulo": "Sempre foi voce",
                    "autor": "Carrie Elks",
                    "imagem_url": "https://m.media-amazon.com/images/I/51HXFdkmFxL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor verdadeiro pode resistir ao tempo.",
                    "comentario_livro": "Sempre foi voce e uma narrativa que explora a conexao entre duas almas, com um enredo que toca o coracao e provoca reflexoes sobre o destino.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "Sempre foi voce"
                },
                {
                    "id_livro": 66,
                    "titulo": "Os olhos do dragao",
                    "autor": "Stephen King",
                    "imagem_url": "https://m.media-amazon.com/images/I/51fu8akxwXL._SY445_SX342_.jpg",
                    "trecho_livro": "Um conto de fadas com um toque sombrio.",
                    "comentario_livro": "Os olhos do dragao e uma obra que mistura fantasia e intriga politica, com personagens complexos e uma narrativa envolvente que cativa o leitor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "conto de fadas",
                    "colecao_nome": "Stephen King"
                },
                {
                    "id_livro": 67,
                    "titulo": "Breakable",
                    "autor": "Tammara Webber",
                    "imagem_url": "https://m.media-amazon.com/images/I/51D0pelEqGL._SY445_SX342_.jpg",
                    "trecho_livro": "A fragilidade da vida e do amor.",
                    "comentario_livro": "Breakable e uma narrativa que explora os desafios emocionais e as superacoes, com personagens que lutam por seus sonhos e por amor.",
                    "classificacao_livro": 4,
                    "categoria_nome": "romance",
                    "colecao_nome": "contornos do coração"
                },
                {
                    "id_livro": 68,
                    "titulo": "Dezesseis luas",
                    "autor": "Margaret Stohl",
                    "imagem_url": "https://m.media-amazon.com/images/I/71lX0Bl-pDL._SY425_.jpg",
                    "trecho_livro": "Um amor que desafia as forcas sobrenaturais.",
                    "comentario_livro": "Dezesseis luas e uma historia envolvente que mistura romance e magia, com um enredo que mantem o leitor ansioso por mais.",
                    "classificacao_livro": 5,
                    "categoria_nome": "conto de fadas",
                    "colecao_nome": "Dezesseis luas"
                },
                {
                    "id_livro": 69,
                    "titulo": "A ascensao da meia noite",
                    "autor": "Lara Adrian",
                    "imagem_url": "https://m.media-amazon.com/images/I/4110MRZZU6L._SY445_SX342_.jpg",
                    "trecho_livro": "A luta entre luz e escuridao.",
                    "comentario_livro": "A ascensao da meia noite e uma narrativa que combina romance e acao, com personagens que enfrentam desafios e descobrem o verdadeiro amor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "ascenção"
                },
                {
                    "id_livro": 70,
                    "titulo": "Lick",
                    "autor": "Kylie Scott",
                    "imagem_url": "https://m.media-amazon.com/images/I/51mMuSCjHyL._SY445_SX342_.jpg",
                    "trecho_livro": "A música pode unir coracoes.",
                    "comentario_livro": "Lick e uma historia romântica que explora a vida de músicos e suas complexas relacoes, com um enredo que cativa e emociona.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "lick"
                },
                {
                    "id_livro": 71,
                    "titulo": "Pulsacao",
                    "autor": "Gail McHugh",
                    "imagem_url": "https://m.media-amazon.com/images/I/81xMT6LB6gS._SY425_.jpg",
                    "trecho_livro": "O amor pode ser uma forca transformadora.",
                    "comentario_livro": "Pulsacao e uma narrativa intensa que explora as complexidades do amor e da dor, com personagens que lutam por suas paixoes.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "tensão"
                },
                {
                    "id_livro": 72,
                    "titulo": "A filha do imperio",
                    "autor": "Janny Wurts",
                    "imagem_url": "https://m.media-amazon.com/images/I/41DgqNC-S+L._SY445_SX342_.jpg",
                    "trecho_livro": "Um mundo de intrigas e poder.",
                    "comentario_livro": "A filha do imperio e uma narrativa rica em detalhes que explora a politica e a cultura de um mundo ficticio, com personagens complexos e um enredo envolvente.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "imperio"
                },
                {
                    "id_livro": 73,
                    "titulo": "Anjo mecanico",
                    "autor": "Cassandra Clare",
                    "imagem_url": "https://m.media-amazon.com/images/I/51MbTa+lz2L._SY445_SX342_.jpg",
                    "trecho_livro": "Um misterio que desafia o sobrenatural.",
                    "comentario_livro": "Anjo mecanico e uma obra que combina romance e aventura, com uma trama cheia de reviravoltas e personagens cativantes que prendem a atencao do leitor.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "peças infernais"
                },
                {
                    "id_livro": 74,
                    "titulo": "Principe mecanico",
                    "autor": "Cassandra Clare",
                    "imagem_url": "https://m.media-amazon.com/images/I/519SPxcHSBL._SY445_SX342_.jpg",
                    "trecho_livro": "O amor e a traicao em um mundo magico.",
                    "comentario_livro": "Principe mecanico e uma narrativa envolvente que explora os dilemas do amor e da lealdade, com personagens que enfrentam desafios emocionais profundos.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "peças infernais"
                },
                {
                    "id_livro": 75,
                    "titulo": "Princesa mecanica",
                    "autor": "Cassandra Clare",
                    "imagem_url": "https://m.media-amazon.com/images/I/51BemGWx4SL._SY445_SX342_.jpg",
                    "trecho_livro": "A luta pelo amor e pela liberdade.",
                    "comentario_livro": "Princesa mecanica e uma conclusao epica que amarra todas as pontas soltas da serie, proporcionando um desfecho emocionante e satisfatorio.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "peças infernais"
                },
                {
                    "id_livro": 76,
                    "titulo": "Cidade dos ossos",
                    "autor": "Cassandra Clare",
                    "imagem_url": "https://m.media-amazon.com/images/I/516ZdYOkhDL._SY445_SX342_.jpg",
                    "trecho_livro": "Um mundo oculto de sombras e luz.",
                    "comentario_livro": "Cidade dos ossos e uma introducao fascinante a um universo rico em mitologia e personagens intrigantes, com uma narrativa que cativa desde o inicio.",
                    "classificacao_livro": 5,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "instrumentos mortais"
                },
                {
                    "id_livro": 77,
                    "titulo": "Misterios noturnos",
                    "autor": "J. R. Ward",
                    "imagem_url": "https://m.media-amazon.com/images/I/61Us1EHzwwL._SY425_.jpg",
                    "trecho_livro": "Segredos que emergem na escuridao.",
                    "comentario_livro": "Misterios noturnos e uma narrativa envolvente que mistura romance e suspense, mantendo o leitor intrigado com suas reviravoltas inesperadas.",
                    "classificacao_livro": 5,
                    "categoria_nome": "vampiro",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 78,
                    "titulo": "After",
                    "autor": "Anna Todd",
                    "imagem_url": "https://m.media-amazon.com/images/I/810FrINgfYS._SY425_.jpg",
                    "trecho_livro": "Um amor que desafia todas as expectativas.",
                    "comentario_livro": "After e uma historia intensa que explora os altos e baixos de um relacionamento tumultuado, com personagens que evoluem ao longo da narrativa.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "after"
                },
                {
                    "id_livro": 79,
                    "titulo": "After depois da verdade",
                    "autor": "Anna Todd",
                    "imagem_url": "https://m.media-amazon.com/images/I/41SStGHQ2hL._SY445_SX342_.jpg",
                    "trecho_livro": "A verdade pode ser dolorosa, mas necessaria.",
                    "comentario_livro": "After depois da verdade e uma continuacao que aprofunda os conflitos emocionais dos personagens, revelando segredos que mudam tudo.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "after"
                },
                {
                    "id_livro": 80,
                    "titulo": "After depois do desencontro",
                    "autor": "Anna Todd",
                    "imagem_url": "https://m.media-amazon.com/images/I/516YwclwnnS._SY445_SX342_.jpg",
                    "trecho_livro": "O reencontro pode trazer novas esperancas.",
                    "comentario_livro": "After depois do desencontro e uma narrativa que explora a reconciliacao e os desafios de um amor que resiste ao tempo.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "after"
                },
                {
                    "id_livro": 81,
                    "titulo": "50 tons de cinza",
                    "autor": "E L James",
                    "imagem_url": "https://m.media-amazon.com/images/I/51XHQHnyciL._SY445_SX342_.jpg",
                    "trecho_livro": "Um amor que desafia limites e convencoes.",
                    "comentario_livro": "50 tons de cinza e uma narrativa provocativa que explora a dinâmica de poder em um relacionamento, com personagens complexos e uma trama envolvente.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "50 tons de cinza"
                },
                {
                    "id_livro": 82,
                    "titulo": "50 tons mais escuros",
                    "autor": "E L James",
                    "imagem_url": "https://m.media-amazon.com/images/I/51CiNfvevDL._SY445_SX342_.jpg",
                    "trecho_livro": "Os segredos do passado podem ameacar o futuro.",
                    "comentario_livro": "50 tons mais escuros e uma continuacao intensa que aprofunda os conflitos emocionais e os desafios do amor entre os protagonistas.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "50 tons de cinza"
                },
                {
                    "id_livro": 84,
                    "titulo": "Filho do amanha",
                    "autor": "Roberto Bombarde",
                    "imagem_url": "https://m.media-amazon.com/images/I/51ftz1veejL._SY445_SX342_.jpg",
                    "trecho_livro": "Um futuro incerto pode ser moldado por nossas escolhas.",
                    "comentario_livro": "Filho do amanha e uma narrativa que explora as consequencias das decisoes e a luta por um futuro melhor, com personagens que inspiram.",
                    "classificacao_livro": 4,
                    "categoria_nome": "fantasia",
                    "colecao_nome": "livros únicos"
                },
                {
                    "id_livro": 85,
                    "titulo": "Renascenca",
                    "autor": "Oliver Bowden",
                    "imagem_url": "https://m.media-amazon.com/images/I/51W+J7abFdL._SY445_SX342_.jpg",
                    "trecho_livro": "A busca pela redencao em tempos sombrios.",
                    "comentario_livro": "Renascenca e uma narrativa que explora a luta por redencao e a forca do espirito humano, com uma trama envolvente e personagens cativantes.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "assassin's creed"
                },
                {
                    "id_livro": 86,
                    "titulo": "Irmandade",
                    "autor": "Oliver Bowden",
                    "imagem_url": "https://m.media-amazon.com/images/I/41JUKfBWxhL._SY445_SX342_.jpg",
                    "trecho_livro": "Lacos que unem em tempos de crise.",
                    "comentario_livro": "Irmandade e uma narrativa que explora a forca das relacoes humanas em meio a desafios, com personagens que enfrentam dilemas morais e emocionais.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "assassin's creed"
                },
                {
                    "id_livro": 87,
                    "titulo": "Cruzada secreta",
                    "autor": "Oliver Bowden",
                    "imagem_url": "https://m.media-amazon.com/images/I/51JbDJM1vAL._SY445_SX342_.jpg",
                    "trecho_livro": "Uma luta pela verdade em um mundo de mentiras.",
                    "comentario_livro": "Cruzada secreta e uma obra que combina acao e intriga, levando o leitor a uma jornada emocionante repleta de reviravoltas e descobertas.",
                    "classificacao_livro": 4,
                    "categoria_nome": "ficcao",
                    "colecao_nome": "assassin's creed"
                },
                {
                    "id_livro": 63,
                    "titulo": "Um toque de vermelho",
                    "autor": "Sylvia Day",
                    "imagem_url": "https://m.media-amazon.com/images/I/41fLxFCEW0L._SY445_SX342_.jpg",
                    "trecho_livro": "A paixao pode ser intensa e transformadora.",
                    "comentario_livro": "Um toque de vermelho e uma narrativa que explora os limites do desejo e da entrega, com personagens que desafiam as normas sociais.",
                    "classificacao_livro": 5,
                    "categoria_nome": "anjo",
                    "colecao_nome": "renegade angels"
                },
                {
                    "id_livro": 83,
                    "titulo": "50 tons de liberdade",
                    "autor": "E L James",
                    "imagem_url": "https://static.estantevirtual.com.br/book/00/GEW-8260-000/GEW-8260-000_detail1.jpg?ts=1736636483861&ims=fit-in/600x800/filters:fill(fff):quality(100)",
                    "trecho_livro": "A busca pela liberdade em um amor complexo.",
                    "comentario_livro": "50 tons de liberdade e um desfecho emocionante que traz à tona os dilemas do amor e da liberdade, proporcionando uma conclusao satisfatoria.",
                    "classificacao_livro": 5,
                    "categoria_nome": "romance",
                    "colecao_nome": "50 tons de cinza"
                }

            ])
        }, 1000)
    })
}